var patterns=[
{name: "Amphitryon",
craft: "knitting",
pay: false,
yarn_name: "Cascade 220",
yarn_weight: "Worsted",
category: "hat",
needles: ["US Size 5", "US Size 7"],
yardage: "160-220 yards",
size:"Women's Medium",
description:"",
pictures:["amphitryon_back.JPG", "amphitryon_back_distant.JPG", "amphitryon_left.JPG", "amphitryon_merino_back.JPG", "amphitryon_side_dist.JPG", "amphitryon_wire.JPG"],
thumbnail:"amphitryon_side_dist.JPG",
pattern_pdf:"/amphitryon.pdf",
rav_link:"https://www.ravelry.com/patterns/library/amphitryon"
},
{name: "Blackberry Leaves",
craft: "knitting",
pay: true,
cost:"$4.00 USD",
yarn_name: "Knit Picks Comfy Fingering",
yarn_weight: "Fingering",
category: "scarf",
needles: ["US Size 6"],
yardage: "420-500 yards",
size:"13.5 x 72 inches after blocking",
description:"",
pictures:["blackberry_front.jpg", "blackberry_back.jpg", "blackberry_end.jpg", "blackberry_shoulder.jpg", "blackberry_start.jpg"],
thumbnail:"blackberry_front.jpg",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/blackberry-leaves"
},
{name: "Calamistrata",
craft: "knitting",
pay: true,
cost: "$4.00 USD",
yarn_name: "Malabrigo Merino Worsted",
yarn_weight: "Worsted",
category: "scarf",
needles: ["US Size 8"],
yardage: "400-500 yards",
size:"7 x 72 inches",
description:"",
pictures:["cala_both.jpg", "cala_left.jpg", "cala_right.jpg"],
thumbnail:"cala_both.jpg",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/calamistrata"
},
{name: "Camden",
craft: "knitting",
pay: true,
cost: "$4.00 USD",
yarn_name: "Knit Picks Stroll Sport",
yarn_weight: "Sport",
category: "clothes",
needles: ["US Size 3", "US Size 4"],
yardage: "400-1000 yards",
size:"3-6 (6-12, 12-18, 18-24) months",
description:"",
pictures:["camden_angle.JPG", "camden_flat.JPG", "camden_hood.JPG"],
thumbnail:"",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/camden-3"
},
{name: "Chioni",
craft: "knitting",
pay: false,
yarn_name: "Plymouth Superwash Worsted",
yarn_weight: "Worsted",
category: "cowl",
needles: ["US Size 6"],
yardage: "500-660 yards",
size:"",
description:"",
pictures:["chioni_close.jpg", "chioni_flat.jpg", "chioni_open.jpg", "chioni_wrapped.jpg"],
thumbnail:"chioni_open.jpg", 
pattern_pdf: "/chioni.pdf"
},
{name: "Crooked Cable Cap",
craft: "knitting",
pay: false,
yarn_name: "Cascade Heritage Solids",
yarn_weight: "Fingering",
category: "hat",
needles: ["US Size 2", "US Size 3"],
yardage: "120-220 yards",
size:"Women's S/M & M/L",
description:"",
pictures:["crooked_back_pink.JPG", "crooked_back_red_mom.JPG", "crooked_left_back_red.JPG", "crooked_pink_top.JPG", "crooked_red_top.JPG", "crooked_right_pink.JPG"],
thumbnail:"crooked_right_pink.JPG",
rav_link:"https://www.ravelry.com/patterns/library/crooked-cable-cap"
},
{name: "Drum Beat Cowl",
craft: "knitting",
pay: true,
cost: "$4.00",
yarn_name: "Miss Babs Yowza!",
yarn_weight: "Worsted",
category: "cowl",
needles: ["US Size 6"],
yardage: "500 yards",
size:"",
description:"",
pictures:["Drumbeat_Cowl.jpg", "drumbeat_flat.jpg", "Drumbeat_wrapped.jpg"],
thumbnail:"Drumbeat_Cowl.jpg",
rav_link:"https://www.ravelry.com/patterns/library/crooked-cable-cap"
},
{name: "Fairy Glen",
craft: "knitting",
pay: true,
cost: "$6.00",
yarn_name: "Knit Picks Capretta",
yarn_weight: "Fingering",
category: "shawl",
needles: ["US Size 6"],
yardage: "500-660 yards",
size:"",
description:"",
pictures:["fairy_back.jpg", "fairy_end.jpg", "fairy_front.jpg"],
thumbnail:"fairy_back.jpg",
rav_link:"https://www.ravelry.com/patterns/library/crooked-cable-cap"
},
]
module.exports=patterns;