var patterns=[
{name: "Amphitryon",
craft: "knitting",
pay: false,
yarn_name: "Cascade 220",
yarn_weight: "Worsted",
category: "hat",
needles: ["US Size 5", "US Size 7"],
yardage: "160-220 yards",
size:"Women's Medium",
description:"",
pictures:[],
thumbnail:"",
pattern_pdf:"/amphitryon.pdf",
rav_link:"https://www.ravelry.com/patterns/library/amphitryon"
},
{name: "Blackberry Leaves",
craft: "knitting",
pay: true,
cost:"$4.00 USD",
yarn_name: "Knit Picks Comfy Fingering",
yarn_weight: "Fingering",
category: "scarf",
needles: ["US Size 6"],
yardage: "420-500 yards",
size:"13.5 x 72 inches after blocking",
description:"",
pictures:[],
thumbnail:"",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/blackberry-leaves"
},
{name: "Calamistrata",
craft: "knitting",
pay: true,
cost: "$4.00 USD",
yarn_name: "Malabrigo Merino Worsted",
yarn_weight: "Worsted",
category: "scarf",
needles: ["US Size 8"],
yardage: "400-500 yards",
size:"7 x 72 inches",
description:"",
pictures:[],
thumbnail:"",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/calamistrata"
},
{name: "Camden",
craft: "knitting",
pay: true,
cost: "$4.00 USD",
yarn_name: "Knit Picks Stroll Sport",
yarn_weight: "Sport",
category: "clothes",
needles: ["US Size 3", "US Size 4"],
yardage: "400-1000 yards",
size:"3-6 (6-12, 12-18, 18-24) months",
description:"",
pictures:[],
thumbnail:"",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/camden-3"
},
{name: "Crooked Cable Cap",
craft: "knitting",
pay: false,
yarn_name: "Cascade Heritage Solids",
yarn_weight: "Fingering",
category: "hat",
needles: ["US Size 2", "US Size 3"],
yardage: "120-220 yards",
size:"Women's S/M & M/L",
description:"",
pictures:[],
thumbnail:"",
cart:'http://www.ravelry.com/purchase/knits-who-say-needle/196020',
rav_link:"https://www.ravelry.com/patterns/library/crooked-cable-cap"
},
]
module.exports=patterns;